name: Lint Backend - Ruff (Python)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend
          python -m venv venv
          venv/bin/pip install -r requirements.txt

      - name: Lint
        run: |
          cd backend
          venv/bin/ruff check .

      - name: Format
        run: |
          cd backend
          venv/bin/ruff format .
